import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY || '';

// Initialize the client
const ai = new GoogleGenAI({ apiKey });

/**
 * Generates a sticker version of the uploaded image.
 * We ask Gemini to generate the subject on a pure green background
 * so we can easily remove it later.
 */
export const generateStickerImage = async (base64Image: string): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing.");
  }

  // Clean the base64 string if it contains the header
  const base64Data = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  try {
    const model = 'gemini-2.5-flash-image';

    const prompt = `
      Create a high-quality die-cut sticker design based on the main subject of this image.
      1. Identify the main subject clearly.
      2. Add a thick, smooth white border (outline) around the subject, simulating a sticker cutline.
      3. CRITICAL: The background MUST be a solid, pure bright green color (RGB: 0, 255, 0; Hex: #00FF00). It must be flat and uniform with NO gradients, NO shadows, and NO patterns.
      4. Keep the subject realistic but polished.
      5. Output ONLY the image.
    `;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            text: prompt
          },
          {
            inlineData: {
              mimeType: 'image/png', // Assuming PNG for input, API handles conversion usually
              data: base64Data
            }
          }
        ]
      }
    });

    // Check for image parts in the response
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by Gemini.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "Failed to generate sticker.");
  }
};